spring:
  h2:
    console:
      enabled: 'true'
  datasource:
    username: sa
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

server:
  port: 9999